---
abstract: 'interface to offliberty.com download service'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Offliberty
no_index:
  directory:
    - t
    - inc
requires:
  HTML::TreeBuilder: 0
  LWP::UserAgent: 0
  perl: 5.014000
resources:
  repository: http://git.ieval.ro/?p=www-offliberty.git
version: 0.001
